== Generate SSH key

% ssh-keygen -t ed25519 -C "your_email@example.com"

# Save the private key to ~/.ssh/hyteio.github.com/id_ed25519
# Use a 128 character password

== Add key to ssh-agent so password is 'remembered'

Start the ssh-agent
% eval "$(ssh-agent -s)"

Add the key to remember the password for this terminal profile session
% ssh-add --apple-use-keychain ~/.ssh/hyteio.github.com/id_ed25519

== Setup for SSH key based authentication

Add the following at the top of ~/.ssh/config:

Host hyteio.github.com
  HostName github.com
  User git
  IdentityFile ~/.ssh/hyteio.github.com/id_ed25519
  UseKeychain yes
  UserKnownHostsFile ~/.ssh/hyteio.github.com/known_hosts

== Configure for commit signing

git config user.name "First Last name"
git config user.email "email@address.com"
git config gpg.format ssh
git config user.signingkey "$HOME/.ssh/hyteio.github.com/id_ed25519.pub"
git config commit.gpgsign true
git config tag.gpgsign true

== Clone the git repo

# Note the hostname alias 'hyteio.github.com'
% git clone git@hyteio.github.com:hyteio/moda-coffee.git

== Commit Description

The commit description should contain a link to a ticket describing the change
in the format [#<ticket-number>]
